package com.mrickar.hearthstonedeckhelper.domain.model.card_model

enum class Keyword(val keyword:String,val description:String) {
    TAUNT(keyword = "Taunt", description = "Enemies must attack minions that have Taunt."),
    SPELL_DAMAGE(keyword = "Spell Damage", description = "Your spells deal extra damage."),
    DIVINE_SHIELD(keyword = "Divine Shield", description = "The first time a Shielded minion takes damage, ignore it."),
    CHARGE(keyword = "Charge", description = "Can attack immediately."),
    SECRET(keyword = "Secret", description = "Hidden until a specific action occurs on your opponent's turn."),
    STEALTH(keyword = "Stealth", description = "Can't be attacked or targeted until it attacks."),
    BATTLECRY(keyword = "Battlecry", description = "Does something when you play it from your hand."),
    FREEZE(keyword = "Freeze", description = "Frozen characters lose their next attack."),
    WINDFURY(keyword = "Windfury", description = "Can attack twice each turn."),
    DEATHRATTLE(keyword = "Deathrattle", description = "Does something when it dies."),
    COMBO(keyword = "Combo", description = "A bonus if you already played a card this turn."),
    OVERLOAD(keyword = "Overload", description = "Cards with Overload limit your mana next turn."),
    SILENCE(keyword = "Silence", description = "Removes all card text and enchantments."),
    COUNTER(keyword = "Counter", description = "A card that is Countered has no effect."),
    IMMUNE(keyword = "Immune", description = "Immune characters can't be damaged."),
    SPARE_PARTS(keyword = "Spare Parts", description = "Spare Parts are 1-Cost spells with minor effects."),
    INSPIRE(keyword = "Inspire", description = "Does something after you use your Hero Power."),
    DISCOVER(keyword = "Discover", description = "Choose one of three cards to add to your hand."),
    CTHUN_OLD_GOD(keyword = "C'Thun, Old God", description = "C'Thun receives buffs no matter where it is, even in your deck!"),
    QUEST(keyword = "Quest", description = "Starts in your hand. Complete for a reward."),
    POISONOUS(keyword = "Poisonous", description = "Destroy any minion damaged by this."),
    ADAPT(keyword = "Adapt", description = "Choose one of 3 bonuses."),
    LIFESTEAL(keyword = "Lifesteal", description = "Damage dealt also heals your hero."),
    RECRUIT(keyword = "Recruit", description = "Summon a minion from your deck."),
    ECHO(keyword = "Echo", description = "Repeatable the turn you play this. Copies can't cost less than (1)."),
    RUSH(keyword = "Rush", description = "Can attack minions immediately."),
    OVERKILL(keyword = "Overkill", description = "Deal excess damage on your turn for a bonus."),
    START_OF_GAME(keyword = "Start of Game", description = "Does something before the first turn."),
    MAGNETIC(keyword = "Magnetic", description = "Play this to the left of a Mech to fuse them together!"),
    LACKEY(keyword = "Lackey", description = "Lackeys are 1-Cost minions with Battlecries."),
    TWINSPELL(keyword = "Twinspell", description = "Can be cast twice."),
    MEGA_WINDFURY(keyword = "Mega-Windfury", description = "Can attack four times each turn."),
    REBORN(keyword = "Reborn", description = "Resurrects with 1 Health the first time it dies."),
    INVOKE(keyword = "Invoke", description = "Use Galakrond's Power."),
    OUTCAST(keyword = "Outcast", description = "A bonus if played as the left- or right-most card in hand."),
    SPELLBURST(keyword = "Spellburst", description = "A one-time effect after you cast a spell."),
    SIDEQUEST(keyword = "Sidequest", description = "Complete for a reward."),
    CORRUPT(keyword = "Corrupt", description = "Upgrades in hand after you play a card that costs more."),
    START_OF_COMBAT(keyword = "Start of Combat", description = "Does something at the start of the Combat Phase."),
    QUESTLINE(keyword = "Questline", description = "Starts in your hand. Complete for a reward, up to 3 times!"),
    TRADEABLE(keyword = "Tradeable", description = "Drag this into your deck to spend 1 Mana and draw a new card."),
    FRENZY(keyword = "Frenzy", description = "A one-time effect after this survives damage."),
    HONORABLE_KILL(keyword = "Honorable Kill", description = "Deal exact lethal damage on your turn for a bonus."),
    NATURE_SPELL_DAMAGE(keyword = "Nature Spell Damage", description = "Your Nature spells deal extra damage."),
    BLOOD_GEM(keyword = "Blood Gem", description = "A spell that gives a friendly minion +1/+1."),
    AVENGE(keyword = "Avenge (X)", description = "Does something after X friendly minions die."),
    COLOSSAL(keyword = "Colossal +X", description = "When summoned, spawns X additional appendages."),
    DREDGE(keyword = "Dredge", description = "Look at the bottom 3 cards of your deck. Put one on top."),
    SPELLCRAFT(keyword = "Spellcraft", description = "Get a temporary spell every turn."),
    ALLIED(keyword = "Allied", description = "Your hero becomes the Allied class after you select this treasure."),
    INFUSE(keyword = "Infuse", description = "Upgrades in hand after X friendly minions die."),
    EMPTY(keyword = "", description = "")
}